# Generated by Django 5.0.6 on 2024-11-30 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
        ('hods', '0002_alter_faculty_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('college_name', models.CharField(default='Your College Name', max_length=255)),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_title', models.CharField(blank=True, max_length=255, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('event_date_time', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('gps_image', models.ImageField(blank=True, null=True, upload_to='gps_images/')),
                ('normal_image', models.ImageField(blank=True, null=True, upload_to='normal_images/')),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('faculty_coordinator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_students_attended', models.IntegerField(blank=True, null=True)),
                ('classes_attended', models.CharField(blank=True, max_length=255, null=True)),
                ('approval_letter', models.FileField(blank=True, null=True, upload_to='approval_letters/')),
                ('speaker_details', models.TextField(blank=True, null=True)),
                ('extra_fields', models.JSONField(default=dict)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hods.faculty')),
            ],
        ),
    ]
