# Generated by Django 5.1.3 on 2024-12-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0002_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
