# Generated by Django 5.0.6 on 2024-11-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0002_reporttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_title', models.CharField(max_length=100)),
                ('objective', models.TextField()),
                ('event_date_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
                ('faculty_coordinator_name', models.CharField(max_length=100)),
                ('students_attended', models.IntegerField()),
                ('classes_attended', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='event_logos/')),
            ],
        ),
    ]
